# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'Available'), (2, b'UNAVAILABLE')], default=1, verbose_name=b'status')),
                ('creator', models.ForeignKey(help_text=b'The user which created the offer', on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
