# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_space', '0002_parkingspace_allocated_to'),
        ('offer', '0003_auto_20180612_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='parking_space',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='parking_space.ParkingSpace'),
        ),
    ]
