# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0004_offer_parking_space'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, b'Available'), (2, b'Unavailable'), (3, b'Deleted by the creator')], default=1, verbose_name=b'status'),
        ),
    ]
