# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The Parking name', max_length=128, verbose_name='Parking name')),
            ],
        ),
    ]
