# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 10:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='The request type', max_length=128, verbose_name='Request type')),
                ('requestedAt', models.CharField(help_text='Requested at', max_length=128, verbose_name='Requested at')),
                ('period', models.CharField(help_text='period', max_length=128, verbose_name='period')),
                ('requestedFor', models.CharField(help_text='requested for', max_length=128, verbose_name='Requested for')),
                ('createdBy', models.CharField(help_text='created by', max_length=128, verbose_name='created by')),
                ('requestedFrom', models.CharField(help_text='Request from', max_length=128, verbose_name='Request from')),
                ('reservationRequestedAt', models.CharField(help_text='The request type', max_length=128, verbose_name='rezervation requested at')),
                ('rentalRequestedAt', models.CharField(help_text='rental requested at ', max_length=128, verbose_name='rental requested at')),
                ('parkingNo', models.IntegerField(verbose_name='parking number')),
            ],
        ),
        migrations.RemoveField(
            model_name='parking',
            name='name',
        ),
    ]
