# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_requesttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='parking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='parking.Parking', verbose_name='Parking'),
        ),
    ]
