# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-09 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_requesttype_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='parking',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='requestTypes', to='parking.Parking', verbose_name='Parking'),
        ),
    ]
