# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_auto_20180109_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='createdBy',
            field=models.CharField(blank=True, help_text='created by', max_length=128, verbose_name='created by'),
        ),
        migrations.AlterField(
            model_name='request',
            name='parking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='parking.Parking', verbose_name='Parking'),
        ),
        migrations.AlterField(
            model_name='request',
            name='parkingNo',
            field=models.IntegerField(blank=True, null=True, verbose_name='parking number'),
        ),
        migrations.AlterField(
            model_name='request',
            name='period',
            field=models.CharField(blank=True, help_text='period', max_length=128, verbose_name='period'),
        ),
        migrations.AlterField(
            model_name='request',
            name='rentalRequestedAt',
            field=models.CharField(blank=True, help_text='rental requested at ', max_length=128, verbose_name='rental requested at'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestedAt',
            field=models.CharField(blank=True, help_text='Requested at', max_length=128, verbose_name='Requested at'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestedFor',
            field=models.CharField(blank=True, help_text='requested for', max_length=128, verbose_name='Requested for'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestedFrom',
            field=models.CharField(blank=True, help_text='Request from', max_length=128, verbose_name='Request from'),
        ),
        migrations.AlterField(
            model_name='request',
            name='reservationRequestedAt',
            field=models.CharField(blank=True, help_text='The request type', max_length=128, verbose_name='rezervation requested at'),
        ),
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(blank=True, help_text='The request type', max_length=128, verbose_name='Request type'),
        ),
    ]
