# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20180110_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='parking',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='parking.Parking', verbose_name='Parking'),
        ),
    ]
