#local_celeryconfig.py
BROKER_URL = 'amqp://localhost/'
CELERY_RESULT_BACKEND = 'amqp://'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'Canada/Eastern'
CELERY_ENABLE_UTC = True
CELERY_DISABLE_RATE_LIMITS = True
