# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_auto_20180612_1213'),
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='parking',
            field=models.ForeignKey(default=9, help_text='The parking where the camera belongs', on_delete=django.db.models.deletion.CASCADE, to='parking.Parking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='url',
            field=models.TextField(default=1, help_text='The video stream url'),
            preserve_default=False,
        ),
    ]
