# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('camera', '__first__'),
        ('parking', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text=b'Identifier provided by the parking admin', max_length=300)),
                ('upper_right_x', models.IntegerField(verbose_name=b'Upper Right x')),
                ('upper_right_y', models.IntegerField(verbose_name=b'Upper Right y')),
                ('bottom_left_x', models.IntegerField(verbose_name=b'Bottom Left x')),
                ('bottom_left_y', models.IntegerField(verbose_name=b'Bottom Left y')),
                ('is_occupied', models.BooleanField(default=False)),
                ('times_extended', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='camera.Camera', verbose_name=b'Camera input')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='parking.Parking')),
            ],
        ),
    ]
