# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('parking_space', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspace',
            name='allocated_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_spaces', to='account.Account'),
        ),
    ]
