# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-26 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '__first__'),
        ('offer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.PositiveSmallIntegerField(choices=[(1, b'Ask for subscription'), (2, b'Request an offer')], help_text=b'The type of request', verbose_name=b'request type')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, b'Pending'), (2, b'Accepted'), (3, b'Rejected')], default=1, verbose_name=b'status')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offer.Offer')),
            ],
        ),
    ]
