# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_requests', to='account.Account'),
        ),
        migrations.AlterField(
            model_name='request',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='offer.Offer'),
        ),
    ]
