# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-12 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_auto_20180612_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='was_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
