# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-14 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_request_was_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='request_type',
        ),
    ]
